version: '2'

services:
  frontend:
    build:
      dockerfile: ./ci/Dockerfile
      context: .
      args:
        port_to_expose: 5000
    image: react-test:0.0.1
    container_name: react-test-cont
    ports:
      - '5000:3000'
